### ISSUE TITLE
Dat - next phase

### ISSUE THREAD

**Issue by mafintosh** [datproject/comm-comm#149]
As many of you may or may not know, a lot of the Dat org has been pretty stale the last +year, outside of the community related stuff. However things have been moving steadily ahead on the development on all the Hyper modules backing Dat.

I have often heard how the relationship between all of these have always been confusing to folks,
 who works on what, who's funded by Dat, who isn't?. 

As part of that convo we have consolidated the core tech that's been driving the Dat project the last many years into it's own organisation, as the Hypercore Protocol, https://hypercore-protocol.org and moved all the relevant modules into a Github org, https://github.com/hypercore-protocol.

Part of this change is to make it more clear how all the pieces fit together, who works on what, and what the supported stack is - just more clarity all around.

There is an announcement post as well here, https://blog.hypercore-protocol.org/posts/announcing-hyperdrive-10/ and a blog post on the Dat blog as well https://blog.datproject.org/2020/05/15/dat-protocol-renamed-hypercore-protocol/

As part of the launch of the next generation of the protocol Beaker also launched it's 1.0 Beta with full support. I suggest you try that out and give some feedback, https://beakerbrowser.com as well.

If anyone has any questions feel free to reach to me.

**Comment by martinheidegger** [comment]
See more about this on youtube: https://youtu.be/Cm9fwxnXg9k and https://youtu.be/mx52uO5SP7A
