### ISSUE TITLE
20201028 - meeting

### ISSUE THREAD

**Issue by ninabreznik** [datproject/comm-comm#173]
Just an hour hanging out and talking about DAT stuff.

:point_right: **Post a comment in this github issue with any topics you'd like to cover this week**

:alarm_clock: Time: 28 Oct 2020, 19:00 Europe/Berlin

:link: https://zoom.us/j/181036238 (Native)
:link: https://zoom.us/wc/join/181036238?pwd= (Web)

| Timezone      |  Date/Time           |
| ------------- |:-------------:|
| Buenos Aires  | 28 10, 4 PM |
| Toronto       | 28 10, 3 PM      |
| New York      | 28 10, 3 PM      |
| Los Angeles   | 28 10, 12 PM      |
| Berlin        | 28 10, 8 PM      |

Or in your local time: https://www.timeanddate.com/worldclock/fixedtime.html?msg=Dat+Comm-Comm+Meeting+2020-10-28&iso=20201028T19&p1=1440&ah=1

**Comment by ninabreznik** [comment]
@serapath will share a logger library he is working on which uses hyper stuff. Can probably more share what he intends to use it for and the concept and plans - not sure if he can demo something already.

**Comment by DougAnderson444** [comment]
I think the timeanddate link is supposed to be somethign like this:
[https://www.timeanddate.com/worldclock/fixedtime.html?msg=Dat+Comm-Comm+Meeting+20201028T19&iso=20201028T19&p1=1440&ah=1](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Dat+Comm-Comm+Meeting+20201028T19&iso=20201028T19&p1=1440&ah=1)?

**Comment by ninabreznik** [comment]
Thanks, @DougAnderson444 for noticing. Fixed!

**Comment by martinheidegger** [comment]
@ninabreznik have there been any notes?

**Comment by ninabreznik** [comment]
From our comm comm meeting? We were waiting for 15min and the left, so we
didn't have one...

**Comment by martinheidegger** [comment]
😿
