### ISSUE TITLE
Looking for things in the community

### ISSUE THREAD

**Issue by martinheidegger** [datproject/comm-comm#39]
_Link:_ https://www.notion.so/datnotes/Dat-Field-Notes-e764f7f830f74763aeb10f57d3a2d4d8
_Call for Action:_ Comments/feedback welcome.

@joehand mentioned in the dat chat:
> Hey all, been trying to collect/write up dat-related things. Going to be keeping them [here](https://www.notion.so/datnotes/Dat-Field-Notes-e764f7f830f74763aeb10f57d3a2d4d8).  And ideally most of these things would move to collaborative spaces =). Any feedback/comments welcome. Thanks!

**Comment by cblgh** [comment]
@joehand  pitching in with a few of the resources i've made here and there

https://github.com/cblgh/hyperdb-examples
https://lhs.nu/archive#dat
https://github.com/cblgh/decent-dat-intro
https://gist.github.com/cblgh/1239ea17337ea11aea369ae3a4c77983
https://gist.github.com/cblgh/b40d664e8fc1e7687ce67b08d05e163a
https://cblgh.org/host-on-dat.html
https://cblgh.org/bots-on-dat.html (kind of outdated)

**Comment by cblgh** [comment]
also ps i love field notes 🖤

**Comment by martinheidegger** [comment]
Two resources of mine.
https://docs.google.com/presentation/d/1ryM43_-ol4X9TJ_H5JBOwvyPr3lgyJ18uvJ_735fxsA/edit
https://docs.google.com/presentation/d/1s8Qoj_OM4j_bwe3_fd1cAS6ljAeuoqBnIOLvi2jH9PU/edit

**Comment by joehand** [comment]
Thanks! I've added those to the bottom and will categorize at some point. 

Put a short blog post out on this: https://blog.datproject.org/2019/03/19/dat-field-notes/
