### ISSUE TITLE
move comm-comm.datproject.org to comm-comm.dat.foundation

### ISSUE THREAD

**Issue by todrobbins** [datproject/comm-comm#70]
Now that the Dat project homepage is located at [dat.foundation](https://dat.foundation/), it would be good to migrate the DNS config to **comm-comm.dat.foundation** to avoid confusion. Or perhaps **comm-comm.dat.land** would be better?

Thoughts?

**Comment by martinheidegger** [comment]
cc. @joehand

**Comment by joehand** [comment]
[Part of a larger discussion to be had]

dat.foundation will likely just exist by itself, without any subdomains attached to it. For all the other dat-related websites, we'll try to consolidate a bit to one site to rule them all. As part of the end of the [MOSS Grant](https://github.com/datproject/organization/issues/1), @whoisgina will be evaluating our existing sites and user onboarding process.

For funzies, here are some of our sites:

### Websites:

- docs.datproject.org
    - User docs to rule them all
- dat.land
    - To consolidate
- dat.foundation
- datprotocol.com
- comm-comm.datproject.org
- events.datproject.org
- datbase.org
    - To archive
- blog.datproject.org
- how dat works (datprotocol.com)
- (broken) chat.datproject.org
- [https://dat.discourse.group/](https://dat.discourse.group/)
- [https://datproject.github.io/design/](https://datproject.github.io/design/)

## Github Organizations:

- github.com/datproject
- github.com/datprotocol
- github.com/dat-foundation
- github.com/dat-land

**Comment by todrobbins** [comment]
Oh wow, yeah that is quite a bit more complicated than I initially thought. Is there any documentation about how these various projects connect and are managed? I know CS&S is the steward for the Dat Project, but how else are these projects connected.

**Comment by todrobbins** [comment]
@joehand @whoisgina, I'd love to help with that process. Let me know if there's anything I can do!

**Comment by okdistribute** [comment]
@todrobbins this would be great! do you still have time to help?

**Comment by todrobbins** [comment]
I do. Which pieces can I help with? I can deal with DNS if that's helpful.

**Comment by okdistribute** [comment]
I think it's OK as-is.

**Comment by okdistribute** [comment]
But it might be helpful to put a link to this page from https://dat.foundation and https://datprotocol.com..!

**Comment by todrobbins** [comment]
@RangerMauve should we create an issue on the other repo?

**Comment by RangerMauve** [comment]
@todrobbins Like, on the dat.foundation website? Yeah, that's a good idea.

**Comment by todrobbins** [comment]
😆 yes, that one! I'll create an issue/add the link.

**Comment by todrobbins** [comment]
Added: datproject/dat-foundation-website/issues/166
