### ISSUE TITLE
Merging `datproject` and `dat-land` organizations on GitHub

### ISSUE THREAD

**Issue by okdistribute** [datproject/comm-comm#97]
We want to merge `datproject` and `dat-land` organizations into a single software foundation called dat-foundation.

This would also be paired with updates to the [dat.foundation website](https://dat.foundation) which were researched and prepared by @whoisgina, which would make the comm-comm more front-and-center, as well as the consortium of projects that govern the documentation & events. This will make it easier for people to curate all of the related repositories & create a horizontal governance structure, to raise all boats! :)

The proposed method I'm thinking about, which is open for feedback here, would be;
1. Rename datproject to dat-foundation
2. Delete/Deprecate/archive repositories in datproject that we won't be maintaining
3. Move dat-land repositories to dat-foundation
4. Add people from dat-land to dat-foundation organization in the same roles they have in dat-land
5. Co-create a process by which people are added/removed from roles in the dat-foundation GitHub organization 

There are likely other ways to do this, does anyone have feedback on this? 

_Deadline:_  2019 09 27
_Link:_ https://dat.foundation
_Call for Action:_
* What do you think about this change?
* What do you think about the process? Any suggestions/improvements?
* Would this affect your participation in comm-comm meetings?
* Could you attend 'developer experience' working groups once a month for coordinating some of the on-the-ground work?
* Would you be able & willing to assist in crafting/defining further the membership process for dat-foundation organization?

**Comment by joehand** [comment]
Check out the proposed sitemap at https://dat.discourse.group/t/rebuilding-the-dat-website-proposed-site-map/79/10

**Comment by martinheidegger** [comment]
> What do you think about this change?

>> Rename datproject to dat-foundation

If others feel good about this, I have no problem with it. _(this repo is on dat-land)_ - a question though: is SEO better for "dat foundation". Can it be found on the interwebs?

>> Delete/Deprecate/archive repositories in datproject that we won't be maintaining

I would love to see a short document explaining the decision why delete/deprecate/archive a certain project and also a feedback mechanism that allows to apply for restart a project from community members.

>> Move dat-land repositories to dat-foundation

No problem.

>> Add people from dat-land to dat-foundation organization in the same roles they have in dat-land

Hmm, this sounds problematic. Some people may have signed up to dat-land because its not related to the foundation?! _(just a guess)_ My suggestion is to ask the member first if they are okay with it. This could also be used as an opportunity to strengthen a relationship to the contributors?!

>> Co-create a process by which people are added/removed from roles in the dat-foundation GitHub organization

If there is a Repo/PR to look at, you can feel free to ping me and I will try to look at it within a week.

> What do you think about the process? Any suggestions/improvements?

I fail to to see a "mission" statement or goal for the dat foundation. It is not clear what people sign up for. This ambiguity is common for projects everywhere and and stressful to all the projects I have ever contributed. Things that are missing for me:

- What does the foundation commit to?
- Where is the border between "core" modules and "user-land" _(how are they decided?)_. 
- What are my powers/responsibilities by me and other members of the community.

> Would this affect your participation in comm-comm meetings?

No.

> Could you attend 'developer experience' working groups once a month for coordinating some of the on-the-ground work?

This would be good to be adjacent to comm-comm meetings (before/after them)

> Would you be able & willing to assist in crafting/defining further the membership process for dat-foundation organization?

The channels are open. I am not available on IRC but other than that... :)

**Comment by chartgerink** [comment]
Deletion may break a bunch of links, which is my main worry after just reading this. Maybe move and archiving to be able to delete the organizations?

I also wanted to ask whether this would be a good time to consolidate the third organization, datprotocol, or whether that's out of scope for this proposal? (I've been confused many times when cloning).

I do think dat-foundation is a clear catch all for things related to Dat :)

(I haven't participated in comm-comm before)

**Comment by okdistribute** [comment]
> > What do you think about this change?
> 
> > > Rename datproject to dat-foundation
> 
> If others feel good about this, I have no problem with it. _(this repo is on dat-land)_ - a question though: is SEO better for "dat foundation". Can it be found on the interwebs?

It seems to be working well! We also discussed 'dat collective' but really, the foundation is just about having a thin layer of non-profit status for developer experience work & accepting grants to redirect to community members!

> 
> > > Delete/Deprecate/archive repositories in datproject that we won't be maintaining
> 
> I would love to see a short document explaining the decision why delete/deprecate/archive a certain project and also a feedback mechanism that allows to apply for restart a project from community members.

We can not delete repos, but maybe clearly stating there is no one maintaining it is enough.

> > > Add people from dat-land to dat-foundation organization in the same roles they have in dat-land
> 
> Hmm, this sounds problematic. Some people may have signed up to dat-land because its not related to the foundation?! _(just a guess)_ My suggestion is to ask the member first if they are okay with it. This could also be used as an opportunity to strengthen a relationship to the contributors?!
> 

OK good idea. 

> > > Co-create a process by which people are added/removed from roles in the dat-foundation GitHub organization
> 
> If there is a Repo/PR to look at, you can feel free to ping me and I will try to look at it within a week.
If you have suggestions, we're all ears! Also @RangerMauve is interested in thinking about this! We should probably collaborate on these bylaws with everyone involved :)
> 
> > What do you think about the process? Any suggestions/improvements?
> 
> I fail to to see a "mission" statement or goal for the dat foundation. It is not clear what people sign up for. This ambiguity is common for projects everywhere and and stressful to all the projects I have ever contributed. Things that are missing for me:

The mission statement could be made more clear, thanks for that. We recently updated the website: [dat.foundation](https//dat.foundation) if that's helpful. 

"The Dat Foundation is a small non-profit group that provides social and technical infrastructure for the consortium of projects and working groups that help build the Dat Protocol."

There are more website updates coming down the pipe from @whoisgina which could also help clear this up!

**Comment by martinheidegger** [comment]
> It seems to be working well! We also discussed 'dat collective' but really, the foundation is just about having a thin layer of non-profit status for developer experience work & accepting grants to redirect to community members!

That alone makes this change important.
  
> We can not delete repos, but maybe clearly stating there is no one maintaining it is enough.

That is the case for some projects, but others might be:

- Has become irrelevant
- Has proven impractical
- Has been integrated through X
- Has been succeeded by Y
 
> "The Dat Foundation is a small non-profit group that provides social and technical infrastructure for the consortium of projects and working groups that help build the Dat Protocol."

:thinking: That is a good explanation for categorization dat-foundation from an outside perspective.
I think it should be expanded for a contributor perspective. (maybe not at the same place)

> There are more website updates coming down the pipe from @whoisgina which could also help clear this up!

Looking forward to them!

**Comment by okdistribute** [comment]
OK I thought about this more and it makes sense that on github we could keep the name `datproject` and move repositories & people from dat-land into datproject, for the following reasons:

1. Fewer broken links!
2. dat.foundation is just a legal entity, it doesn't need any code in it
3. dat-land and datproject have basically become the same thing

any other thoughts regarding this before we do it?

**Comment by okdistribute** [comment]
started moving stuff to datproject org!

**Comment by RangerMauve** [comment]
Great job Karissa! 💜
